name: salon_client
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icon_forest: ^1.1.8
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.13.1
  fluttertoast: ^8.2.4  
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  booking_calendar: ^1.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets :
      - assets/icons/
